import { createContext, useContext, useState, ReactNode } from 'react';

export interface Language {
  code: string;
  label: string;
  country: string;
  suggested?: boolean;
}

export const LANGUAGES: Language[] = [
  { code: 'en',     label: 'English (UK)',            country: 'gb',  suggested: true },
  { code: 'en-us',  label: 'English (USA)',           country: 'us',  suggested: true },
  { code: 'fr',     label: 'Français',                country: 'fr',  suggested: true },
  { code: 'pt',     label: 'Português (Portugal)',    country: 'pt',  suggested: true },
  { code: 'sq',     label: 'Shqip',                   country: 'al' },
  { code: 'ar',     label: 'العربية',                 country: 'sa' },
  { code: 'bg',     label: 'Български',               country: 'bg' },
  { code: 'cs',     label: 'Čeština',                 country: 'cz' },
  { code: 'da',     label: 'Dansk',                   country: 'dk' },
  { code: 'de',     label: 'Deutsch',                 country: 'de' },
  { code: 'de-at',  label: 'Deutsch (Österreich)',    country: 'at' },
  { code: 'de-ch',  label: 'Deutsch (Schweiz)',       country: 'ch' },
  { code: 'en-ca',  label: 'English (Canada)',        country: 'ca' },
  { code: 'en-ie',  label: 'English (Ireland)',       country: 'ie' },
  { code: 'en-int', label: 'English (International)', country: 'un' },
  { code: 'es',     label: 'Español',                 country: 'es' },
  { code: 'el',     label: 'Ελληνικά',               country: 'gr' },
  { code: 'fr-ca',  label: 'Français (Canada)',       country: 'ca' },
  { code: 'hr',     label: 'Hrvatski',                country: 'hr' },
  { code: 'hu',     label: 'Magyar',                  country: 'hu' },
  { code: 'it',     label: 'Italiano',                country: 'it' },
  { code: 'nl',     label: 'Nederlands',              country: 'nl' },
  { code: 'no',     label: 'Norsk',                   country: 'no' },
  { code: 'pl',     label: 'Polski',                  country: 'pl' },
  { code: 'pt-br',  label: 'Português (Brasil)',      country: 'br' },
  { code: 'ro',     label: 'Română',                  country: 'ro' },
  { code: 'ru',     label: 'Русский',                 country: 'ru' },
  { code: 'mo',     label: 'Молдовеняскэ',            country: 'md' },
  { code: 'fi',     label: 'Suomi',                   country: 'fi' },
  { code: 'sv',     label: 'Svenska',                 country: 'se' },
  { code: 'tr',     label: 'Türkçe',                  country: 'tr' },
  { code: 'uk',     label: 'Українська',              country: 'ua' },
  { code: 'zh',     label: '汉语',                    country: 'cn' },
];

export function flagUrl(country: string, size: 'w20' | 'w40' | 'w80' = 'w20') {
  return `https://flagcdn.com/${size}/${country}.png`;
}

// ─── Translations ────────────────────────────────────────────────────────────

export type TranslationKey =
  | 'hero.title1' | 'hero.title2' | 'hero.subtitle'
  | 'hero.cta' | 'hero.how'
  | 'hero.stat.max' | 'hero.stat.lookback' | 'hero.stat.success' | 'hero.stat.payout'
  | 'hero.stat.max_label' | 'hero.stat.lookback_label' | 'hero.stat.success_label' | 'hero.stat.payout_label'
  | 'nav.home' | 'nav.about' | 'nav.how' | 'nav.fees' | 'nav.claim' | 'nav.myclaims' | 'nav.signin'
  | 'checker.badge' | 'checker.title' | 'checker.sub'
  | 'checker.from' | 'checker.to' | 'checker.flight' | 'checker.date' | 'checker.airline' | 'checker.what' | 'checker.reason'
  | 'checker.btn' | 'checker.analyzing' | 'checker.reason_placeholder'
  | 'checker.select' | 'checker.select_airline' | 'checker.select_issue'
  | 'steps.badge' | 'steps.title'
  | 'steps.1.title' | 'steps.1.desc'
  | 'steps.2.title' | 'steps.2.desc'
  | 'steps.3.title' | 'steps.3.desc'
  | 'faq.title' | 'faq.badge'
  | 'cta.title' | 'cta.sub' | 'cta.btn'
  | 'trust.ssl' | 'trust.fee' | 'trust.ai' | 'trust.flights' | 'trust.reviews'
  | 'available_in'
  | 'result.nextsteps' | 'result.claim_btn' | 'result.estimated';

type Translations = Record<TranslationKey, string>;
type LangMap = Partial<Record<string, Partial<Translations>>>;

const base: Translations = {
  'hero.title1': 'Delayed or Canceled Flight?',
  'hero.title2': 'Get Up to $650!',
  'hero.subtitle': 'We fight the airlines so you don\'t have to. Submit in minutes — our experts handle everything.',
  'hero.cta': 'Start Now — It\'s Free',
  'hero.how': 'Our Process',
  'hero.stat.max': '$650', 'hero.stat.max_label': 'Max per passenger',
  'hero.stat.lookback': '3 yrs', 'hero.stat.lookback_label': 'Look-back period',
  'hero.stat.success': '99%', 'hero.stat.success_label': 'Success rate',
  'hero.stat.payout': '21d', 'hero.stat.payout_label': 'Avg. payout time',
  'nav.home': 'Home', 'nav.about': 'About Us', 'nav.how': 'How It Works',
  'nav.fees': 'Our Fees', 'nav.claim': 'New Claim', 'nav.myclaims': 'My Claims', 'nav.signin': 'Sign In',
  'checker.badge': 'Free AI check — 60 seconds',
  'checker.title': 'Was your flight eligible?',
  'checker.sub': 'Claude AI instantly checks EC 261/2004 eligibility.',
  'checker.from': 'From', 'checker.to': 'To',
  'checker.flight': 'Flight Number', 'checker.date': 'Flight Date',
  'checker.airline': 'Airline', 'checker.what': 'What happened?',
  'checker.reason': 'Reason given by airline (optional)',
  'checker.reason_placeholder': 'e.g. technical fault, weather, crew shortage...',
  'checker.btn': 'Check My Flight — Free',
  'checker.analyzing': 'Claude AI is analyzing...',
  'checker.select': 'Select...', 'checker.select_airline': 'Select...', 'checker.select_issue': 'Select...',
  'steps.badge': 'Our Process', 'steps.title': 'Get Your Compensation in 3 Steps',
  'steps.1.title': 'Submit Your Flight Details', 'steps.1.desc': 'Fill out our simple form in under two minutes. All we need is your flight number and date.',
  'steps.2.title': 'We Build Your Case', 'steps.2.desc': 'Our experts verify your eligibility and compile all necessary documentation to build a strong claim.',
  'steps.3.title': 'You Get Paid', 'steps.3.desc': 'We handle all negotiations. Once the airline pays, we transfer your compensation directly to you, minus our 50% fee.',
  'faq.title': 'Frequently Asked Questions', 'faq.badge': 'FAQ',
  'cta.title': "Ready to Claim What's Yours?",
  'cta.sub': 'Free check, no commitment. Thousands of passengers already paid.',
  'cta.btn': 'Start Now — It\'s Free',
  'trust.ssl': 'SSL & GDPR Compliant', 'trust.fee': 'No Win, No Fee — 50%',
  'trust.ai': 'AI Powered', 'trust.flights': 'All major airlines', 'trust.reviews': '4.9/5 · 5,200+ reviews',
  'available_in': 'Available in',
  'result.nextsteps': 'Next steps:', 'result.claim_btn': 'Start my claim — no upfront cost →',
  'result.estimated': 'Estimated:',
};

const translations: LangMap = {
  'fr': {
    'hero.title1': 'Réclamez jusqu\'à',
    'hero.title2': 'pour vols retardés ou annulés',
    'hero.subtitle': 'Vérification IA rapide. Sans paiement initial. On ne touche que si vous gagnez.',
    'hero.cta': 'Vérifier mon vol — Gratuit',
    'hero.how': 'Comment ça marche',
    'hero.stat.max_label': 'Max par passager',
    'hero.stat.lookback_label': 'Période de réclamation',
    'hero.stat.success_label': 'Taux de succès',
    'hero.stat.payout_label': 'Délai moyen de paiement',
    'nav.home': 'Accueil', 'nav.about': 'À propos', 'nav.how': 'Comment ça marche',
    'nav.fees': 'Nos frais', 'nav.claim': 'Nouvelle réclamation', 'nav.myclaims': 'Mes réclamations', 'nav.signin': 'Connexion',
    'checker.badge': 'Vérification IA gratuite — 60 secondes',
    'checker.title': 'Votre vol était-il éligible ?',
    'checker.sub': 'Claude AI vérifie instantanément l\'éligibilité EC 261/2004.',
    'checker.from': 'De', 'checker.to': 'À',
    'checker.flight': 'Numéro de vol', 'checker.date': 'Date du vol',
    'checker.airline': 'Compagnie', 'checker.what': 'Que s\'est-il passé ?',
    'checker.reason': 'Raison donnée par la compagnie (optionnel)',
    'checker.reason_placeholder': 'ex: panne technique, météo, manque d\'équipage...',
    'checker.btn': 'Vérifier mon vol — Gratuit',
    'checker.analyzing': 'Claude AI analyse...',
    'checker.select': 'Sélectionner...', 'checker.select_airline': 'Sélectionner...', 'checker.select_issue': 'Sélectionner...',
    'steps.badge': 'Processus simple', 'steps.title': '3 étapes pour votre indemnisation',
    'steps.1.title': 'Vérifier l\'éligibilité', 'steps.1.desc': 'Entrez les détails de votre vol. Notre IA vérifie EC 261/2004 en quelques secondes.',
    'steps.2.title': 'Soumettre & signer', 'steps.2.desc': 'Téléchargez vos documents et signez la procuration numériquement. Moins de 5 minutes.',
    'steps.3.title': 'Être payé', 'steps.3.desc': 'Nous combattons la compagnie. Vous recevez jusqu\'à €600 directement. Nous prenons 25% seulement si nous gagnons.',
    'faq.title': 'Questions fréquentes', 'faq.badge': 'FAQ',
    'cta.title': 'Prêt à réclamer votre argent ?',
    'cta.sub': 'Vérification gratuite, sans engagement. Des milliers de passagers indemnisés.',
    'cta.btn': 'Vérifier mon vol — Gratuit',
    'trust.ssl': 'SSL & RGPD Conforme', 'trust.fee': 'Sans victoire sans frais — 25%',
    'trust.ai': 'Propulsé par Claude AI', 'trust.flights': 'Tous vols UE & UK', 'trust.reviews': '4,8/5 · 3 841 avis',
    'available_in': 'Disponible en',
    'result.nextsteps': 'Prochaines étapes :', 'result.claim_btn': 'Démarrer ma réclamation — sans frais →',
    'result.estimated': 'Estimé :',
  },
  'de': {
    'hero.title1': 'Fordern Sie bis zu',
    'hero.title2': 'für verspätete oder annullierte Flüge',
    'hero.subtitle': 'Schnelle KI-Prüfung. Keine Vorauszahlung. Wir verdienen nur, wenn Sie gewinnen.',
    'hero.cta': 'Meinen Flug prüfen — Kostenlos',
    'hero.how': 'So funktioniert es',
    'hero.stat.max_label': 'Max pro Passagier',
    'hero.stat.lookback_label': 'Rückwirkungszeitraum',
    'hero.stat.success_label': 'Erfolgsquote',
    'hero.stat.payout_label': 'Durchschnittliche Auszahlungszeit',
    'nav.home': 'Startseite', 'nav.about': 'Über uns', 'nav.how': 'So funktioniert es',
    'nav.fees': 'Unsere Gebühren', 'nav.claim': 'Neuer Antrag', 'nav.myclaims': 'Meine Anträge', 'nav.signin': 'Anmelden',
    'checker.badge': 'Kostenlose KI-Prüfung — 60 Sekunden',
    'checker.title': 'War Ihr Flug berechtigt?',
    'checker.sub': 'Claude AI prüft sofort die EC 261/2004 Berechtigung.',
    'checker.from': 'Von', 'checker.to': 'Nach',
    'checker.flight': 'Flugnummer', 'checker.date': 'Flugdatum',
    'checker.airline': 'Fluggesellschaft', 'checker.what': 'Was ist passiert?',
    'checker.reason': 'Grund der Fluggesellschaft (optional)',
    'checker.reason_placeholder': 'z.B. technischer Fehler, Wetter, Personalmangel...',
    'checker.btn': 'Meinen Flug prüfen — Kostenlos',
    'checker.analyzing': 'Claude AI analysiert...',
    'checker.select': 'Auswählen...', 'checker.select_airline': 'Auswählen...', 'checker.select_issue': 'Auswählen...',
    'steps.badge': 'Einfacher Prozess', 'steps.title': '3 Schritte zu Ihrer Entschädigung',
    'steps.1.title': 'Berechtigung prüfen', 'steps.1.desc': 'Geben Sie Ihre Flugdaten ein. Unsere KI prüft EC 261/2004 in Sekunden.',
    'steps.2.title': 'Einreichen & unterschreiben', 'steps.2.desc': 'Dokumente hochladen und Vollmacht digital unterschreiben. Unter 5 Minuten.',
    'steps.3.title': 'Bezahlt werden', 'steps.3.desc': 'Wir kämpfen gegen die Airline. Sie erhalten bis zu €600. Wir nehmen 25% nur bei Erfolg.',
    'faq.title': 'Häufige Fragen', 'faq.badge': 'FAQ',
    'cta.title': 'Bereit, Ihr Geld zurückzufordern?',
    'cta.sub': 'Kostenlose Prüfung, keine Verpflichtung. Tausende von Passagieren entschädigt.',
    'cta.btn': 'Meinen Flug prüfen — Kostenlos',
    'trust.ssl': 'SSL & DSGVO konform', 'trust.fee': 'Kein Erfolg, keine Gebühr — 25%',
    'trust.ai': 'Claude AI betrieben', 'trust.flights': 'Alle EU & UK Flüge', 'trust.reviews': '4,8/5 · 3.841 Bewertungen',
    'available_in': 'Verfügbar in',
    'result.nextsteps': 'Nächste Schritte:', 'result.claim_btn': 'Meinen Antrag starten — kostenlos →',
    'result.estimated': 'Geschätzt:',
  },
  'es': {
    'hero.title1': 'Reclama hasta',
    'hero.title2': 'por vuelos retrasados o cancelados',
    'hero.subtitle': 'Verificación IA rápida. Sin pago inicial. Solo cobramos si ganamos.',
    'hero.cta': 'Verificar mi vuelo — Gratis',
    'hero.how': 'Cómo funciona',
    'hero.stat.max_label': 'Máx. por pasajero',
    'hero.stat.lookback_label': 'Período de reclamación',
    'hero.stat.success_label': 'Tasa de éxito',
    'hero.stat.payout_label': 'Tiempo promedio de pago',
    'nav.home': 'Inicio', 'nav.about': 'Sobre nosotros', 'nav.how': 'Cómo funciona',
    'nav.fees': 'Nuestras tarifas', 'nav.claim': 'Nueva reclamación', 'nav.myclaims': 'Mis reclamaciones', 'nav.signin': 'Iniciar sesión',
    'checker.badge': 'Verificación IA gratuita — 60 segundos',
    'checker.title': '¿Era elegible tu vuelo?',
    'checker.sub': 'Claude AI verifica instantáneamente la elegibilidad EC 261/2004.',
    'checker.from': 'Desde', 'checker.to': 'Hasta',
    'checker.flight': 'Número de vuelo', 'checker.date': 'Fecha del vuelo',
    'checker.airline': 'Aerolínea', 'checker.what': '¿Qué pasó?',
    'checker.reason': 'Razón de la aerolínea (opcional)',
    'checker.reason_placeholder': 'ej: fallo técnico, clima, escasez de tripulación...',
    'checker.btn': 'Verificar mi vuelo — Gratis',
    'checker.analyzing': 'Claude AI está analizando...',
    'checker.select': 'Seleccionar...', 'checker.select_airline': 'Seleccionar...', 'checker.select_issue': 'Seleccionar...',
    'steps.badge': 'Proceso simple', 'steps.title': '3 pasos para tu compensación',
    'steps.1.title': 'Verificar elegibilidad', 'steps.1.desc': 'Ingresa los datos de tu vuelo. Nuestra IA verifica EC 261/2004 en segundos.',
    'steps.2.title': 'Enviar y firmar', 'steps.2.desc': 'Sube tus documentos y firma la autorización digitalmente. Menos de 5 minutos.',
    'steps.3.title': 'Recibir pago', 'steps.3.desc': 'Luchamos contra la aerolínea. Recibes hasta €600. Cobramos 25% solo si ganamos.',
    'faq.title': 'Preguntas frecuentes', 'faq.badge': 'FAQ',
    'cta.title': '¿Listo para reclamar lo tuyo?',
    'cta.sub': 'Verificación gratuita, sin compromiso. Miles de pasajeros compensados.',
    'cta.btn': 'Verificar mi vuelo — Gratis',
    'trust.ssl': 'SSL y RGPD conforme', 'trust.fee': 'Sin éxito sin cargo — 25%',
    'trust.ai': 'Impulsado por Claude AI', 'trust.flights': 'Todos los vuelos UE y UK', 'trust.reviews': '4,8/5 · 3.841 reseñas',
    'available_in': 'Disponible en',
    'result.nextsteps': 'Próximos pasos:', 'result.claim_btn': 'Iniciar mi reclamación — sin coste →',
    'result.estimated': 'Estimado:',
  },
  'pt': {
    'hero.title1': 'Reclame até',
    'hero.title2': 'por voos atrasados ou cancelados',
    'hero.subtitle': 'Verificação IA rápida. Sem pagamento antecipado. Só recebemos se ganhar.',
    'hero.cta': 'Verificar o meu voo — Grátis',
    'hero.how': 'Como funciona',
    'hero.stat.max_label': 'Máx. por passageiro',
    'hero.stat.lookback_label': 'Período de reclamação',
    'hero.stat.success_label': 'Taxa de sucesso',
    'hero.stat.payout_label': 'Tempo médio de pagamento',
    'nav.home': 'Início', 'nav.about': 'Sobre nós', 'nav.how': 'Como funciona',
    'nav.fees': 'As nossas taxas', 'nav.claim': 'Nova reclamação', 'nav.myclaims': 'As minhas reclamações', 'nav.signin': 'Entrar',
    'checker.badge': 'Verificação IA gratuita — 60 segundos',
    'checker.title': 'O seu voo era elegível?',
    'checker.sub': 'Claude AI verifica instantaneamente a elegibilidade EC 261/2004.',
    'checker.from': 'De', 'checker.to': 'Para',
    'checker.flight': 'Número do voo', 'checker.date': 'Data do voo',
    'checker.airline': 'Companhia aérea', 'checker.what': 'O que aconteceu?',
    'checker.reason': 'Motivo da companhia (opcional)',
    'checker.reason_placeholder': 'ex: avaria técnica, mau tempo, falta de tripulação...',
    'checker.btn': 'Verificar o meu voo — Grátis',
    'checker.analyzing': 'Claude AI está a analisar...',
    'checker.select': 'Selecionar...', 'checker.select_airline': 'Selecionar...', 'checker.select_issue': 'Selecionar...',
    'steps.badge': 'Processo simples', 'steps.title': '3 passos para a sua compensação',
    'steps.1.title': 'Verificar elegibilidade', 'steps.1.desc': 'Insira os dados do voo. A nossa IA verifica EC 261/2004 em segundos.',
    'steps.2.title': 'Submeter e assinar', 'steps.2.desc': 'Carregue documentos e assine a procuração digitalmente. Menos de 5 minutos.',
    'steps.3.title': 'Receber pagamento', 'steps.3.desc': 'Lutamos pela sua causa. Recebe até €600. Cobramos 25% só se ganharmos.',
    'faq.title': 'Perguntas frequentes', 'faq.badge': 'FAQ',
    'cta.title': 'Pronto para reclamar o que é seu?',
    'cta.sub': 'Verificação gratuita, sem compromisso. Milhares de passageiros pagos.',
    'cta.btn': 'Verificar o meu voo — Grátis',
    'trust.ssl': 'SSL e RGPD conforme', 'trust.fee': 'Sem vitória sem taxa — 25%',
    'trust.ai': 'Alimentado por Claude AI', 'trust.flights': 'Todos os voos UE e UK', 'trust.reviews': '4,8/5 · 3.841 avaliações',
    'available_in': 'Disponível em',
    'result.nextsteps': 'Próximos passos:', 'result.claim_btn': 'Iniciar reclamação — sem custo →',
    'result.estimated': 'Estimado:',
  },
  'tr': {
    'hero.title1': 'Geç kalan veya iptal',
    'hero.title2': 'edilen uçuşlar için tazminat alın',
    'hero.subtitle': 'Hızlı AI kontrolü. Ön ödeme yok. Yalnızca kazanırsanız ücret alırız.',
    'hero.cta': 'Uçuşumu kontrol et — Ücretsiz',
    'hero.how': 'Nasıl çalışır',
    'hero.stat.max_label': 'Yolcu başına maks.',
    'hero.stat.lookback_label': 'Geriye dönük süre',
    'hero.stat.success_label': 'Başarı oranı',
    'hero.stat.payout_label': 'Ortalama ödeme süresi',
    'nav.home': 'Ana Sayfa', 'nav.about': 'Hakkımızda', 'nav.how': 'Nasıl Çalışır',
    'nav.fees': 'Ücretlerimiz', 'nav.claim': 'Yeni Talep', 'nav.myclaims': 'Taleplerim', 'nav.signin': 'Giriş Yap',
    'checker.badge': 'Ücretsiz AI kontrolü — 60 saniye',
    'checker.title': 'Uçuşunuz hak kazanıyor muydu?',
    'checker.sub': 'Claude AI, EC 261/2004 uygunluğunu anında kontrol eder.',
    'checker.from': 'Nereden', 'checker.to': 'Nereye',
    'checker.flight': 'Uçuş Numarası', 'checker.date': 'Uçuş Tarihi',
    'checker.airline': 'Havayolu', 'checker.what': 'Ne oldu?',
    'checker.reason': 'Havayolunun verdiği neden (isteğe bağlı)',
    'checker.reason_placeholder': 'örn. teknik arıza, hava durumu, personel eksikliği...',
    'checker.btn': 'Uçuşumu kontrol et — Ücretsiz',
    'checker.analyzing': 'Claude AI analiz ediyor...',
    'checker.select': 'Seçin...', 'checker.select_airline': 'Seçin...', 'checker.select_issue': 'Seçin...',
    'steps.badge': 'Basit süreç', 'steps.title': 'Tazminatınız için 3 adım',
    'steps.1.title': 'Uygunluğu kontrol edin', 'steps.1.desc': 'Uçuş bilgilerinizi girin. AI\'mız EC 261/2004\'ü saniyeler içinde kontrol eder.',
    'steps.2.title': 'Gönderin ve imzalayın', 'steps.2.desc': 'Belgelerinizi yükleyin ve vekaletnameyi dijital olarak imzalayın. 5 dakikadan az sürer.',
    'steps.3.title': 'Ödemeyi alın', 'steps.3.desc': 'Havayoluyla savaşıyoruz. €600\'a kadar alırsınız. Yalnızca kazanırsak %25 alırız.',
    'faq.title': 'Sık sorulan sorular', 'faq.badge': 'SSS',
    'cta.title': 'Hakkınızı talep etmeye hazır mısınız?',
    'cta.sub': 'Ücretsiz kontrol, taahhüt yok. Binlerce yolcuya ödeme yapıldı.',
    'cta.btn': 'Uçuşumu kontrol et — Ücretsiz',
    'trust.ssl': 'SSL ve GDPR Uyumlu', 'trust.fee': 'Kazanmazsak ücret almayız — %25',
    'trust.ai': 'Claude AI destekli', 'trust.flights': 'Tüm AB ve İngiltere uçuşları', 'trust.reviews': '4,8/5 · 3.841 yorum',
    'available_in': 'Şurada mevcut',
    'result.nextsteps': 'Sonraki adımlar:', 'result.claim_btn': 'Talebimi başlat — ücretsiz →',
    'result.estimated': 'Tahmini:',
  },
  'uk': {
    'hero.title1': 'Отримайте до',
    'hero.title2': 'за затримані або скасовані рейси',
    'hero.subtitle': 'Швидка перевірка AI. Без передоплати. Платимо лише при успіху.',
    'hero.cta': 'Перевірити мій рейс — Безкоштовно',
    'hero.how': 'Як це працює',
    'hero.stat.max_label': 'Макс. на пасажира',
    'hero.stat.lookback_label': 'Період подачі',
    'hero.stat.success_label': 'Відсоток успіху',
    'hero.stat.payout_label': 'Середній час виплати',
    'nav.home': 'Головна', 'nav.about': 'Про нас', 'nav.how': 'Як це працює',
    'nav.fees': 'Наші тарифи', 'nav.claim': 'Нова заявка', 'nav.myclaims': 'Мої заявки', 'nav.signin': 'Увійти',
    'checker.badge': 'Безкоштовна перевірка AI — 60 секунд',
    'checker.title': 'Ваш рейс має право на компенсацію?',
    'checker.sub': 'Claude AI миттєво перевіряє EC 261/2004.',
    'checker.from': 'Звідки', 'checker.to': 'Куди',
    'checker.flight': 'Номер рейсу', 'checker.date': 'Дата рейсу',
    'checker.airline': 'Авіакомпанія', 'checker.what': 'Що сталося?',
    'checker.reason': 'Причина авіакомпанії (необов\'язково)',
    'checker.reason_placeholder': 'напр. технічна несправність, погода, брак екіпажу...',
    'checker.btn': 'Перевірити мій рейс — Безкоштовно',
    'checker.analyzing': 'Claude AI аналізує...',
    'checker.select': 'Вибрати...', 'checker.select_airline': 'Вибрати...', 'checker.select_issue': 'Вибрати...',
    'steps.badge': 'Простий процес', 'steps.title': '3 кроки до вашої компенсації',
    'steps.1.title': 'Перевірити право', 'steps.1.desc': 'Введіть дані рейсу. Наш AI перевіряє EC 261/2004 за секунди.',
    'steps.2.title': 'Подати і підписати', 'steps.2.desc': 'Завантажте документи і підпишіть довіреність цифровим способом. Менше 5 хвилин.',
    'steps.3.title': 'Отримати виплату', 'steps.3.desc': 'Ми боремося за вас. Ви отримуєте до €600. Беремо 25% лише при успіху.',
    'faq.title': 'Часті запитання', 'faq.badge': 'FAQ',
    'cta.title': 'Готові отримати своє?',
    'cta.sub': 'Безкоштовна перевірка, без зобов\'язань. Тисячі пасажирів отримали виплати.',
    'cta.btn': 'Перевірити мій рейс — Безкоштовно',
    'trust.ssl': 'SSL і GDPR відповідність', 'trust.fee': 'Без результату без оплати — 25%',
    'trust.ai': 'На основі Claude AI', 'trust.flights': 'Усі рейси ЄС та Великобританії', 'trust.reviews': '4,8/5 · 3 841 відгук',
    'available_in': 'Доступно на',
    'result.nextsteps': 'Наступні кроки:', 'result.claim_btn': 'Почати заявку — без витрат →',
    'result.estimated': 'Оцінка:',
  },
  'ar': {
    'hero.title1': 'احصل على تعويض يصل إلى',
    'hero.title2': 'للرحلات المتأخرة أو الملغاة',
    'hero.subtitle': 'فحص فوري بالذكاء الاصطناعي. بدون دفع مسبق. نأخذ أجرنا فقط عند الفوز.',
    'hero.cta': 'فحص رحلتي — مجاناً',
    'hero.how': 'كيف يعمل',
    'hero.stat.max_label': 'الحد الأقصى للراكب',
    'hero.stat.lookback_label': 'فترة المطالبة',
    'hero.stat.success_label': 'معدل النجاح',
    'hero.stat.payout_label': 'متوسط وقت الدفع',
    'nav.home': 'الرئيسية', 'nav.about': 'من نحن', 'nav.how': 'كيف يعمل',
    'nav.fees': 'رسومنا', 'nav.claim': 'مطالبة جديدة', 'nav.myclaims': 'مطالباتي', 'nav.signin': 'تسجيل الدخول',
    'checker.badge': 'فحص مجاني بالذكاء الاصطناعي — 60 ثانية',
    'checker.title': 'هل رحلتك مؤهلة للتعويض؟',
    'checker.sub': 'يتحقق Claude AI فوراً من أهلية EC 261/2004.',
    'checker.from': 'من', 'checker.to': 'إلى',
    'checker.flight': 'رقم الرحلة', 'checker.date': 'تاريخ الرحلة',
    'checker.airline': 'شركة الطيران', 'checker.what': 'ماذا حدث؟',
    'checker.reason': 'سبب شركة الطيران (اختياري)',
    'checker.reason_placeholder': 'مثال: عطل تقني، طقس، نقص طاقم...',
    'checker.btn': 'فحص رحلتي — مجاناً',
    'checker.analyzing': 'Claude AI يحلل...',
    'checker.select': 'اختر...', 'checker.select_airline': 'اختر...', 'checker.select_issue': 'اختر...',
    'steps.badge': 'عملية بسيطة', 'steps.title': '3 خطوات للحصول على تعويضك',
    'steps.1.title': 'فحص الأهلية', 'steps.1.desc': 'أدخل تفاصيل رحلتك. يتحقق الذكاء الاصطناعي من EC 261/2004 في ثوانٍ.',
    'steps.2.title': 'تقديم وتوقيع', 'steps.2.desc': 'ارفع مستنداتك ووقّع التوكيل رقمياً. أقل من 5 دقائق.',
    'steps.3.title': 'استلم المبلغ', 'steps.3.desc': 'نحن نتفاوض مع شركة الطيران. تحصل على €600. نأخذ 25% فقط عند الفوز.',
    'faq.title': 'أسئلة شائعة', 'faq.badge': 'FAQ',
    'cta.title': 'مستعد للمطالبة بحقك؟',
    'cta.sub': 'فحص مجاني، بدون التزام. آلاف الركاب تم تعويضهم.',
    'cta.btn': 'فحص رحلتي — مجاناً',
    'trust.ssl': 'متوافق مع SSL و GDPR', 'trust.fee': 'لا فوز، لا رسوم — 25%',
    'trust.ai': 'مدعوم بـ Claude AI', 'trust.flights': 'جميع رحلات EU و UK', 'trust.reviews': '4.8/5 · 3,841 تقييم',
    'available_in': 'متوفر في',
    'result.nextsteps': 'الخطوات التالية:', 'result.claim_btn': 'ابدأ مطالبتي — بدون تكلفة مسبقة →',
    'result.estimated': 'تقدير:',
  },
  'it': {
    'hero.title1': 'Richiedi fino a',
    'hero.title2': 'per voli in ritardo o cancellati',
    'hero.subtitle': 'Verifica AI rapida. Nessun pagamento anticipato. Paghiamo solo se vinciamo.',
    'hero.cta': 'Verifica il mio volo — Gratis',
    'hero.how': 'Come funziona',
    'hero.stat.max_label': 'Max per passeggero',
    'hero.stat.lookback_label': 'Periodo di reclamo',
    'hero.stat.success_label': 'Tasso di successo',
    'hero.stat.payout_label': 'Tempo medio di pagamento',
    'nav.home': 'Home', 'nav.about': 'Chi siamo', 'nav.how': 'Come funziona',
    'nav.fees': 'Le nostre tariffe', 'nav.claim': 'Nuovo reclamo', 'nav.myclaims': 'I miei reclami', 'nav.signin': 'Accedi',
    'checker.badge': 'Verifica AI gratuita — 60 secondi',
    'checker.title': 'Il tuo volo era idoneo?',
    'checker.sub': 'Claude AI verifica istantaneamente l\'idoneità EC 261/2004.',
    'checker.from': 'Da', 'checker.to': 'A',
    'checker.flight': 'Numero volo', 'checker.date': 'Data volo',
    'checker.airline': 'Compagnia aerea', 'checker.what': 'Cosa è successo?',
    'checker.reason': 'Motivo della compagnia (opzionale)',
    'checker.reason_placeholder': 'es: guasto tecnico, meteo, carenza equipaggio...',
    'checker.btn': 'Verifica il mio volo — Gratis',
    'checker.analyzing': 'Claude AI sta analizzando...',
    'checker.select': 'Seleziona...', 'checker.select_airline': 'Seleziona...', 'checker.select_issue': 'Seleziona...',
    'steps.badge': 'Processo semplice', 'steps.title': '3 passaggi per il tuo risarcimento',
    'steps.1.title': 'Verifica idoneità', 'steps.1.desc': 'Inserisci i dettagli del volo. La nostra AI verifica EC 261/2004 in secondi.',
    'steps.2.title': 'Invia e firma', 'steps.2.desc': 'Carica i documenti e firma la procura digitalmente. Meno di 5 minuti.',
    'steps.3.title': 'Ricevi il pagamento', 'steps.3.desc': 'Combattiamo con la compagnia aerea. Ricevi fino a €600. Prendiamo il 25% solo se vinciamo.',
    'faq.title': 'Domande frequenti', 'faq.badge': 'FAQ',
    'cta.title': 'Pronto a richiedere ciò che ti spetta?',
    'cta.sub': 'Verifica gratuita, nessun impegno. Migliaia di passeggeri risarciti.',
    'cta.btn': 'Verifica il mio volo — Gratis',
    'trust.ssl': 'SSL & GDPR Conforme', 'trust.fee': 'Nessun successo, nessuna tariffa — 25%',
    'trust.ai': 'Powered by Claude AI', 'trust.flights': 'Tutti i voli EU & UK', 'trust.reviews': '4,8/5 · 3.841 recensioni',
    'available_in': 'Disponibile in',
    'result.nextsteps': 'Prossimi passi:', 'result.claim_btn': 'Avvia il mio reclamo — senza costi →',
    'result.estimated': 'Stimato:',
  },
  'nl': {
    'hero.title1': 'Claim tot',
    'hero.title2': 'voor vertraagde of geannuleerde vluchten',
    'hero.subtitle': 'Snelle AI-check. Geen vooruitbetaling. Wij verdienen alleen als u wint.',
    'hero.cta': 'Controleer mijn vlucht — Gratis',
    'hero.how': 'Hoe het werkt',
    'hero.stat.max_label': 'Max per passagier',
    'hero.stat.lookback_label': 'Terugkijkperiode',
    'hero.stat.success_label': 'Slagingspercentage',
    'hero.stat.payout_label': 'Gemiddelde uitbetalingstijd',
    'nav.home': 'Home', 'nav.about': 'Over ons', 'nav.how': 'Hoe het werkt',
    'nav.fees': 'Onze kosten', 'nav.claim': 'Nieuwe claim', 'nav.myclaims': 'Mijn claims', 'nav.signin': 'Inloggen',
    'checker.badge': 'Gratis AI-check — 60 seconden',
    'checker.title': 'Was uw vlucht in aanmerking?',
    'checker.sub': 'Claude AI controleert direct de EC 261/2004-geschiktheid.',
    'checker.from': 'Van', 'checker.to': 'Naar',
    'checker.flight': 'Vluchtnummer', 'checker.date': 'Vluchtdatum',
    'checker.airline': 'Luchtvaartmaatschappij', 'checker.what': 'Wat is er gebeurd?',
    'checker.reason': 'Reden van de maatschappij (optioneel)',
    'checker.reason_placeholder': 'bijv. technisch defect, weer, personeelstekort...',
    'checker.btn': 'Controleer mijn vlucht — Gratis',
    'checker.analyzing': 'Claude AI analyseert...',
    'checker.select': 'Selecteer...', 'checker.select_airline': 'Selecteer...', 'checker.select_issue': 'Selecteer...',
    'steps.badge': 'Eenvoudig proces', 'steps.title': '3 stappen naar uw vergoeding',
    'steps.1.title': 'Geschiktheid controleren', 'steps.1.desc': 'Voer uw vluchtgegevens in. Onze AI controleert EC 261/2004 in seconden.',
    'steps.2.title': 'Indienen & ondertekenen', 'steps.2.desc': 'Upload uw documenten en onderteken de volmacht digitaal. Minder dan 5 minuten.',
    'steps.3.title': 'Betaald worden', 'steps.3.desc': 'Wij strijden met de maatschappij. U ontvangt tot €600. Wij nemen 25% alleen bij succes.',
    'faq.title': 'Veelgestelde vragen', 'faq.badge': 'FAQ',
    'cta.title': 'Klaar om te claimen wat van u is?',
    'cta.sub': 'Gratis check, geen verplichtingen. Duizenden passagiers uitbetaald.',
    'cta.btn': 'Controleer mijn vlucht — Gratis',
    'trust.ssl': 'SSL & GDPR Conform', 'trust.fee': 'Geen succes, geen kosten — 25%',
    'trust.ai': 'Aangedreven door Claude AI', 'trust.flights': 'Alle EU & UK-vluchten', 'trust.reviews': '4,8/5 · 3.841 beoordelingen',
    'available_in': 'Beschikbaar in',
    'result.nextsteps': 'Volgende stappen:', 'result.claim_btn': 'Start mijn claim — geen vooruitkosten →',
    'result.estimated': 'Geschat:',
  },
  'pl': {
    'hero.title1': 'Odzyskaj do',
    'hero.title2': 'za opóźniony lub odwołany lot',
    'hero.subtitle': 'Szybka weryfikacja AI. Bez opłat z góry. Płacisz tylko gdy wygramy.',
    'hero.cta': 'Sprawdź mój lot — Bezpłatnie',
    'hero.how': 'Jak to działa',
    'hero.stat.max_label': 'Maks. na pasażera',
    'hero.stat.lookback_label': 'Okres wsteczny',
    'hero.stat.success_label': 'Wskaźnik sukcesu',
    'hero.stat.payout_label': 'Średni czas wypłaty',
    'nav.home': 'Strona główna', 'nav.about': 'O nas', 'nav.how': 'Jak to działa',
    'nav.fees': 'Nasze opłaty', 'nav.claim': 'Nowe roszczenie', 'nav.myclaims': 'Moje roszczenia', 'nav.signin': 'Zaloguj się',
    'checker.badge': 'Bezpłatna weryfikacja AI — 60 sekund',
    'checker.title': 'Czy Twój lot był uprawniony?',
    'checker.sub': 'Claude AI natychmiast sprawdza uprawnienie EC 261/2004.',
    'checker.from': 'Z', 'checker.to': 'Do',
    'checker.flight': 'Numer lotu', 'checker.date': 'Data lotu',
    'checker.airline': 'Linia lotnicza', 'checker.what': 'Co się stało?',
    'checker.reason': 'Powód podany przez linię (opcjonalnie)',
    'checker.reason_placeholder': 'np. usterka techniczna, pogoda, brak załogi...',
    'checker.btn': 'Sprawdź mój lot — Bezpłatnie',
    'checker.analyzing': 'Claude AI analizuje...',
    'checker.select': 'Wybierz...', 'checker.select_airline': 'Wybierz...', 'checker.select_issue': 'Wybierz...',
    'steps.badge': 'Prosty proces', 'steps.title': '3 kroki do Twojego odszkodowania',
    'steps.1.title': 'Sprawdź uprawnienie', 'steps.1.desc': 'Wpisz dane lotu. Nasze AI sprawdza EC 261/2004 w sekundy.',
    'steps.2.title': 'Złóż i podpisz', 'steps.2.desc': 'Wgraj dokumenty i podpisz pełnomocnictwo cyfrowo. Poniżej 5 minut.',
    'steps.3.title': 'Otrzymaj wypłatę', 'steps.3.desc': 'Walczymy z linią lotniczą. Otrzymujesz do €600. Bierzemy 25% tylko przy sukcesie.',
    'faq.title': 'Często zadawane pytania', 'faq.badge': 'FAQ',
    'cta.title': 'Gotowy, by odzyskać swoje pieniądze?',
    'cta.sub': 'Bezpłatna weryfikacja, bez zobowiązań. Tysiące pasażerów otrzymało odszkodowania.',
    'cta.btn': 'Sprawdź mój lot — Bezpłatnie',
    'trust.ssl': 'SSL & RODO Zgodny', 'trust.fee': 'Brak sukcesu, brak opłaty — 25%',
    'trust.ai': 'Napędzany przez Claude AI', 'trust.flights': 'Wszystkie loty UE & UK', 'trust.reviews': '4,8/5 · 3 841 opinii',
    'available_in': 'Dostępne w',
    'result.nextsteps': 'Następne kroki:', 'result.claim_btn': 'Rozpocznij roszczenie — bez kosztów →',
    'result.estimated': 'Szacunkowo:',
  },
  'ru': {
    'hero.title1': 'Получите до',
    'hero.title2': 'за задержанные или отменённые рейсы',
    'hero.subtitle': 'Быстрая проверка ИИ. Без предоплаты. Мы берём оплату только при успехе.',
    'hero.cta': 'Проверить рейс — Бесплатно',
    'hero.how': 'Как это работает',
    'hero.stat.max_label': 'Макс. на пассажира',
    'hero.stat.lookback_label': 'Период подачи',
    'hero.stat.success_label': 'Процент успеха',
    'hero.stat.payout_label': 'Среднее время выплаты',
    'nav.home': 'Главная', 'nav.about': 'О нас', 'nav.how': 'Как это работает',
    'nav.fees': 'Наши тарифы', 'nav.claim': 'Новая заявка', 'nav.myclaims': 'Мои заявки', 'nav.signin': 'Войти',
    'checker.badge': 'Бесплатная проверка ИИ — 60 секунд',
    'checker.title': 'Имеет ли ваш рейс право на компенсацию?',
    'checker.sub': 'Claude AI мгновенно проверяет соответствие EC 261/2004.',
    'checker.from': 'Откуда', 'checker.to': 'Куда',
    'checker.flight': 'Номер рейса', 'checker.date': 'Дата рейса',
    'checker.airline': 'Авиакомпания', 'checker.what': 'Что произошло?',
    'checker.reason': 'Причина авиакомпании (необязательно)',
    'checker.reason_placeholder': 'напр. технеисправность, погода, нехватка экипажа...',
    'checker.btn': 'Проверить рейс — Бесплатно',
    'checker.analyzing': 'Claude AI анализирует...',
    'checker.select': 'Выбрать...', 'checker.select_airline': 'Выбрать...', 'checker.select_issue': 'Выбрать...',
    'steps.badge': 'Простой процесс', 'steps.title': '3 шага до вашей компенсации',
    'steps.1.title': 'Проверить право', 'steps.1.desc': 'Введите данные рейса. Наш ИИ проверяет EC 261/2004 за секунды.',
    'steps.2.title': 'Подать и подписать', 'steps.2.desc': 'Загрузите документы и подпишите доверенность цифровым способом. Менее 5 минут.',
    'steps.3.title': 'Получить выплату', 'steps.3.desc': 'Мы боремся с авиакомпанией. Вы получаете до €600. Берём 25% только при успехе.',
    'faq.title': 'Частые вопросы', 'faq.badge': 'FAQ',
    'cta.title': 'Готовы потребовать своё?',
    'cta.sub': 'Бесплатная проверка, без обязательств. Тысячи пассажиров получили выплаты.',
    'cta.btn': 'Проверить рейс — Бесплатно',
    'trust.ssl': 'SSL и GDPR соответствие', 'trust.fee': 'Без результата без оплаты — 25%',
    'trust.ai': 'На основе Claude AI', 'trust.flights': 'Все рейсы ЕС и Великобритании', 'trust.reviews': '4,8/5 · 3 841 отзыв',
    'available_in': 'Доступно в',
    'result.nextsteps': 'Следующие шаги:', 'result.claim_btn': 'Начать заявку — без затрат →',
    'result.estimated': 'Оценочно:',
  },
  'ro': {
    'hero.title1': 'Revendicați până la',
    'hero.title2': 'pentru zboruri întârziate sau anulate',
    'hero.subtitle': 'Verificare AI rapidă. Fără plată în avans. Plătim doar la succes.',
    'hero.cta': 'Verifică zborul meu — Gratuit',
    'hero.how': 'Cum funcționează',
    'hero.stat.max_label': 'Max per pasager',
    'hero.stat.lookback_label': 'Perioadă de revendicare',
    'hero.stat.success_label': 'Rata de succes',
    'hero.stat.payout_label': 'Timp mediu de plată',
    'nav.home': 'Acasă', 'nav.about': 'Despre noi', 'nav.how': 'Cum funcționează',
    'nav.fees': 'Tarifele noastre', 'nav.claim': 'Revendicare nouă', 'nav.myclaims': 'Revendicările mele', 'nav.signin': 'Autentificare',
    'checker.badge': 'Verificare AI gratuită — 60 secunde',
    'checker.title': 'Zborul dvs. a fost eligibil?',
    'checker.sub': 'Claude AI verifică instantaneu eligibilitatea EC 261/2004.',
    'checker.from': 'De la', 'checker.to': 'La',
    'checker.flight': 'Număr zbor', 'checker.date': 'Data zborului',
    'checker.airline': 'Companie aeriană', 'checker.what': 'Ce s-a întâmplat?',
    'checker.reason': 'Motivul companiei (opțional)',
    'checker.reason_placeholder': 'ex: defecțiune tehnică, vreme, lipsă echipaj...',
    'checker.btn': 'Verifică zborul meu — Gratuit',
    'checker.analyzing': 'Claude AI analizează...',
    'checker.select': 'Selectează...', 'checker.select_airline': 'Selectează...', 'checker.select_issue': 'Selectează...',
    'steps.badge': 'Proces simplu', 'steps.title': '3 pași pentru compensația dvs.',
    'steps.1.title': 'Verificați eligibilitatea', 'steps.1.desc': 'Introduceți datele zborului. AI-ul nostru verifică EC 261/2004 în secunde.',
    'steps.2.title': 'Trimiteți și semnați', 'steps.2.desc': 'Încărcați documentele și semnați procura digital. Sub 5 minute.',
    'steps.3.title': 'Primiți plata', 'steps.3.desc': 'Luptăm cu compania aeriană. Primiți până la €600. Luăm 25% doar la succes.',
    'faq.title': 'Întrebări frecvente', 'faq.badge': 'FAQ',
    'cta.title': 'Gata să revendicați ce vi se cuvine?',
    'cta.sub': 'Verificare gratuită, fără angajament. Mii de pasageri plătiți.',
    'cta.btn': 'Verifică zborul meu — Gratuit',
    'trust.ssl': 'SSL & GDPR Conform', 'trust.fee': 'Fără succes, fără taxă — 25%',
    'trust.ai': 'Alimentat de Claude AI', 'trust.flights': 'Toate zborurile UE & UK', 'trust.reviews': '4,8/5 · 3.841 recenzii',
    'available_in': 'Disponibil în',
    'result.nextsteps': 'Pașii următori:', 'result.claim_btn': 'Începe revendicarea — fără costuri →',
    'result.estimated': 'Estimat:',
  },
  'cs': {
    'hero.title1': 'Získejte až',
    'hero.title2': 'za zpožděné nebo zrušené lety',
    'hero.subtitle': 'Rychlá AI kontrola. Bez zálohy. Platíme pouze při úspěchu.',
    'hero.cta': 'Zkontrolovat můj let — Zdarma',
    'hero.how': 'Jak to funguje',
    'hero.stat.max_label': 'Max na cestujícího',
    'hero.stat.lookback_label': 'Zpětné období',
    'hero.stat.success_label': 'Míra úspěšnosti',
    'hero.stat.payout_label': 'Průměrná doba výplaty',
    'nav.home': 'Domů', 'nav.about': 'O nás', 'nav.how': 'Jak to funguje',
    'nav.fees': 'Naše poplatky', 'nav.claim': 'Nová žádost', 'nav.myclaims': 'Moje žádosti', 'nav.signin': 'Přihlásit se',
    'checker.badge': 'Bezplatná AI kontrola — 60 sekund',
    'checker.title': 'Byl váš let způsobilý?',
    'checker.sub': 'Claude AI okamžitě kontroluje způsobilost EC 261/2004.',
    'checker.from': 'Z', 'checker.to': 'Do',
    'checker.flight': 'Číslo letu', 'checker.date': 'Datum letu',
    'checker.airline': 'Letecká společnost', 'checker.what': 'Co se stalo?',
    'checker.reason': 'Důvod letecké společnosti (volitelné)',
    'checker.reason_placeholder': 'např. technická závada, počasí, nedostatek posádky...',
    'checker.btn': 'Zkontrolovat můj let — Zdarma',
    'checker.analyzing': 'Claude AI analyzuje...',
    'checker.select': 'Vyberte...', 'checker.select_airline': 'Vyberte...', 'checker.select_issue': 'Vyberte...',
    'steps.badge': 'Jednoduchý proces', 'steps.title': '3 kroky k vašemu odškodnění',
    'steps.1.title': 'Zkontrolovat způsobilost', 'steps.1.desc': 'Zadejte údaje o letu. Naše AI kontroluje EC 261/2004 během sekund.',
    'steps.2.title': 'Odeslat a podepsat', 'steps.2.desc': 'Nahrajte dokumenty a podepište plnou moc digitálně. Do 5 minut.',
    'steps.3.title': 'Získat výplatu', 'steps.3.desc': 'Bojujeme s leteckou společností. Získáte až €600. Bereme 25% pouze při úspěchu.',
    'faq.title': 'Časté otázky', 'faq.badge': 'FAQ',
    'cta.title': 'Připraveni požadovat to, co vám patří?',
    'cta.sub': 'Bezplatná kontrola, bez závazků. Tisíce cestujících odškodněno.',
    'cta.btn': 'Zkontrolovat můj let — Zdarma',
    'trust.ssl': 'SSL & GDPR Vyhovující', 'trust.fee': 'Bez výhry bez poplatku — 25%',
    'trust.ai': 'Poháněno Claude AI', 'trust.flights': 'Všechny lety EU & UK', 'trust.reviews': '4,8/5 · 3 841 recenzí',
    'available_in': 'Dostupné v',
    'result.nextsteps': 'Další kroky:', 'result.claim_btn': 'Zahájit žádost — bez nákladů →',
    'result.estimated': 'Odhadovaně:',
  },
  'da': {
    'hero.title1': 'Kræv op til',
    'hero.title2': 'for forsinkede eller aflyste fly',
    'hero.subtitle': 'Hurtig AI-kontrol. Ingen forudbetaling. Vi tjener kun, hvis du vinder.',
    'hero.cta': 'Tjek mit fly — Gratis',
    'hero.how': 'Sådan fungerer det',
    'hero.stat.max_label': 'Maks per passager',
    'hero.stat.lookback_label': 'Tilbageskuende periode',
    'hero.stat.success_label': 'Succesrate',
    'hero.stat.payout_label': 'Gennemsnitlig udbetalingstid',
    'nav.home': 'Hjem', 'nav.about': 'Om os', 'nav.how': 'Sådan fungerer det',
    'nav.fees': 'Vores gebyrer', 'nav.claim': 'Ny klage', 'nav.myclaims': 'Mine klager', 'nav.signin': 'Log ind',
    'checker.badge': 'Gratis AI-kontrol — 60 sekunder',
    'checker.title': 'Var dit fly berettiget?',
    'checker.sub': 'Claude AI kontrollerer øjeblikkeligt EC 261/2004-berettigelse.',
    'checker.from': 'Fra', 'checker.to': 'Til',
    'checker.flight': 'Flynummer', 'checker.date': 'Flydato',
    'checker.airline': 'Flyselskab', 'checker.what': 'Hvad skete der?',
    'checker.reason': 'Flyselskabets årsag (valgfrit)',
    'checker.reason_placeholder': 'f.eks. teknisk fejl, vejr, manglende besætning...',
    'checker.btn': 'Tjek mit fly — Gratis',
    'checker.analyzing': 'Claude AI analyserer...',
    'checker.select': 'Vælg...', 'checker.select_airline': 'Vælg...', 'checker.select_issue': 'Vælg...',
    'steps.badge': 'Enkel proces', 'steps.title': '3 trin til din erstatning',
    'steps.1.title': 'Kontroller berettigelse', 'steps.1.desc': 'Indtast dine flyoplysninger. Vores AI kontrollerer EC 261/2004 på sekunder.',
    'steps.2.title': 'Indsend og underskriv', 'steps.2.desc': 'Upload dine dokumenter og underskriv fuldmagten digitalt. Under 5 minutter.',
    'steps.3.title': 'Bliv betalt', 'steps.3.desc': 'Vi kæmper mod flyselskabet. Du modtager op til €600. Vi tager 25% kun ved succes.',
    'faq.title': 'Hyppige spørgsmål', 'faq.badge': 'FAQ',
    'cta.title': 'Klar til at kræve det, der er dit?',
    'cta.sub': 'Gratis kontrol, ingen forpligtelse. Tusindvis af passagerer betalt.',
    'cta.btn': 'Tjek mit fly — Gratis',
    'trust.ssl': 'SSL & GDPR Kompatibel', 'trust.fee': 'Ingen sejr, intet gebyr — 25%',
    'trust.ai': 'Drevet af Claude AI', 'trust.flights': 'Alle EU & UK-fly', 'trust.reviews': '4,8/5 · 3.841 anmeldelser',
    'available_in': 'Tilgængelig i',
    'result.nextsteps': 'Næste skridt:', 'result.claim_btn': 'Start min klage — ingen forudgående omkostninger →',
    'result.estimated': 'Estimeret:',
  },
  'sv': {
    'hero.title1': 'Kräv upp till',
    'hero.title2': 'för försenade eller inställda flyg',
    'hero.subtitle': 'Snabb AI-kontroll. Ingen förskottsbetalning. Vi tar betalt bara vid framgång.',
    'hero.cta': 'Kontrollera mitt flyg — Gratis',
    'hero.how': 'Hur det fungerar',
    'hero.stat.max_label': 'Max per passagerare',
    'hero.stat.lookback_label': 'Återblicksperiod',
    'hero.stat.success_label': 'Framgångsrate',
    'hero.stat.payout_label': 'Genomsnittlig utbetalningstid',
    'nav.home': 'Hem', 'nav.about': 'Om oss', 'nav.how': 'Hur det fungerar',
    'nav.fees': 'Våra avgifter', 'nav.claim': 'Nytt anspråk', 'nav.myclaims': 'Mina anspråk', 'nav.signin': 'Logga in',
    'checker.badge': 'Gratis AI-kontroll — 60 sekunder',
    'checker.title': 'Var ditt flyg berättigat?',
    'checker.sub': 'Claude AI kontrollerar omedelbart EC 261/2004-berättigande.',
    'checker.from': 'Från', 'checker.to': 'Till',
    'checker.flight': 'Flygnummer', 'checker.date': 'Flygdatum',
    'checker.airline': 'Flygbolag', 'checker.what': 'Vad hände?',
    'checker.reason': 'Flygbolagets orsak (valfritt)',
    'checker.reason_placeholder': 'ex. tekniskt fel, väder, brist på besättning...',
    'checker.btn': 'Kontrollera mitt flyg — Gratis',
    'checker.analyzing': 'Claude AI analyserar...',
    'checker.select': 'Välj...', 'checker.select_airline': 'Välj...', 'checker.select_issue': 'Välj...',
    'steps.badge': 'Enkel process', 'steps.title': '3 steg till din ersättning',
    'steps.1.title': 'Kontrollera berättigande', 'steps.1.desc': 'Ange dina flyguppgifter. Vår AI kontrollerar EC 261/2004 på sekunder.',
    'steps.2.title': 'Skicka in & signera', 'steps.2.desc': 'Ladda upp dina dokument och signera fullmakten digitalt. Under 5 minuter.',
    'steps.3.title': 'Få betalt', 'steps.3.desc': 'Vi kämpar mot flygbolaget. Du får upp till €600. Vi tar 25% bara vid framgång.',
    'faq.title': 'Vanliga frågor', 'faq.badge': 'FAQ',
    'cta.title': 'Redo att kräva vad som är ditt?',
    'cta.sub': 'Gratis kontroll, ingen förpliktelse. Tusentals passagerare ersatta.',
    'cta.btn': 'Kontrollera mitt flyg — Gratis',
    'trust.ssl': 'SSL & GDPR Kompatibel', 'trust.fee': 'Ingen vinst, ingen avgift — 25%',
    'trust.ai': 'Driven av Claude AI', 'trust.flights': 'Alla EU & UK-flyg', 'trust.reviews': '4,8/5 · 3 841 recensioner',
    'available_in': 'Tillgänglig i',
    'result.nextsteps': 'Nästa steg:', 'result.claim_btn': 'Starta mitt anspråk — inga förskottskostnader →',
    'result.estimated': 'Uppskattat:',
  },
  'no': {
    'hero.title1': 'Krev opptil',
    'hero.title2': 'for forsinkede eller kansellerte fly',
    'hero.subtitle': 'Rask AI-sjekk. Ingen forskuddsbetaling. Vi tjener bare når du vinner.',
    'hero.cta': 'Sjekk flyet mitt — Gratis',
    'hero.how': 'Slik fungerer det',
    'hero.stat.max_label': 'Maks per passasjer',
    'hero.stat.lookback_label': 'Tilbakevirkende periode',
    'hero.stat.success_label': 'Suksessrate',
    'hero.stat.payout_label': 'Gjennomsnittlig utbetalingstid',
    'nav.home': 'Hjem', 'nav.about': 'Om oss', 'nav.how': 'Slik fungerer det',
    'nav.fees': 'Gebyrene våre', 'nav.claim': 'Ny klage', 'nav.myclaims': 'Mine klager', 'nav.signin': 'Logg inn',
    'checker.badge': 'Gratis AI-sjekk — 60 sekunder',
    'checker.title': 'Var flyet ditt berettiget?',
    'checker.sub': 'Claude AI sjekker øyeblikkelig EC 261/2004-berettigelse.',
    'checker.from': 'Fra', 'checker.to': 'Til',
    'checker.flight': 'Flynummer', 'checker.date': 'Flydato',
    'checker.airline': 'Flyselskap', 'checker.what': 'Hva skjedde?',
    'checker.reason': 'Flyselskapet årsak (valgfritt)',
    'checker.reason_placeholder': 'f.eks. teknisk feil, vær, manglende besetning...',
    'checker.btn': 'Sjekk flyet mitt — Gratis',
    'checker.analyzing': 'Claude AI analyserer...',
    'checker.select': 'Velg...', 'checker.select_airline': 'Velg...', 'checker.select_issue': 'Velg...',
    'steps.badge': 'Enkel prosess', 'steps.title': '3 trinn til erstatningen din',
    'steps.1.title': 'Sjekk berettigelse', 'steps.1.desc': 'Skriv inn flydetaljene dine. Vår AI sjekker EC 261/2004 på sekunder.',
    'steps.2.title': 'Send inn og signer', 'steps.2.desc': 'Last opp dokumentene og signer fullmakten digitalt. Under 5 minutter.',
    'steps.3.title': 'Bli betalt', 'steps.3.desc': 'Vi kjemper mot flyselskapet. Du mottar opptil €600. Vi tar 25% bare ved suksess.',
    'faq.title': 'Vanlige spørsmål', 'faq.badge': 'FAQ',
    'cta.title': 'Klar til å kreve det som er ditt?',
    'cta.sub': 'Gratis sjekk, ingen forpliktelse. Tusenvis av passasjerer betalt.',
    'cta.btn': 'Sjekk flyet mitt — Gratis',
    'trust.ssl': 'SSL & GDPR Kompatibel', 'trust.fee': 'Ingen seier, intet gebyr — 25%',
    'trust.ai': 'Drevet av Claude AI', 'trust.flights': 'Alle EU & UK-fly', 'trust.reviews': '4,8/5 · 3 841 anmeldelser',
    'available_in': 'Tilgjengelig i',
    'result.nextsteps': 'Neste trinn:', 'result.claim_btn': 'Start klagen min — ingen forhåndskostnader →',
    'result.estimated': 'Estimert:',
  },
  'fi': {
    'hero.title1': 'Vaadi jopa',
    'hero.title2': 'viivästyneistä tai perutuista lennoista',
    'hero.subtitle': 'Nopea tekoälytarkistus. Ei ennakkomaksua. Veloitamme vain voitosta.',
    'hero.cta': 'Tarkista lentoni — Ilmaiseksi',
    'hero.how': 'Miten se toimii',
    'hero.stat.max_label': 'Enintään per matkustaja',
    'hero.stat.lookback_label': 'Takautuvuusaika',
    'hero.stat.success_label': 'Onnistumisprosentti',
    'hero.stat.payout_label': 'Keskimääräinen maksuaika',
    'nav.home': 'Etusivu', 'nav.about': 'Tietoa meistä', 'nav.how': 'Miten toimii',
    'nav.fees': 'Palkkiomme', 'nav.claim': 'Uusi vaatimus', 'nav.myclaims': 'Vaatimukseni', 'nav.signin': 'Kirjaudu',
    'checker.badge': 'Ilmainen tekoälytarkistus — 60 sekuntia',
    'checker.title': 'Oliko lentosi oikeutettu?',
    'checker.sub': 'Claude AI tarkistaa EC 261/2004 -oikeuden välittömästi.',
    'checker.from': 'Mistä', 'checker.to': 'Minne',
    'checker.flight': 'Lentonumero', 'checker.date': 'Lentopäivä',
    'checker.airline': 'Lentoyhtiö', 'checker.what': 'Mitä tapahtui?',
    'checker.reason': 'Lentoyhtiön syy (valinnainen)',
    'checker.reason_placeholder': 'esim. tekninen vika, sää, miehistövaje...',
    'checker.btn': 'Tarkista lentoni — Ilmaiseksi',
    'checker.analyzing': 'Claude AI analysoi...',
    'checker.select': 'Valitse...', 'checker.select_airline': 'Valitse...', 'checker.select_issue': 'Valitse...',
    'steps.badge': 'Yksinkertainen prosessi', 'steps.title': '3 askelta korvaukseen',
    'steps.1.title': 'Tarkista oikeus', 'steps.1.desc': 'Syötä lentotietosi. Tekoälymme tarkistaa EC 261/2004 sekunneissa.',
    'steps.2.title': 'Lähetä ja allekirjoita', 'steps.2.desc': 'Lataa asiakirjat ja allekirjoita valtakirja digitaalisesti. Alle 5 minuuttia.',
    'steps.3.title': 'Saa maksu', 'steps.3.desc': 'Taistelemme lentoyhtiötä vastaan. Saat jopa €600. Otamme 25% vain voitosta.',
    'faq.title': 'Usein kysytyt kysymykset', 'faq.badge': 'FAQ',
    'cta.title': 'Valmis vaatimaan omaasi?',
    'cta.sub': 'Ilmainen tarkistus, ei sitoumusta. Tuhansia matkustajia maksettu.',
    'cta.btn': 'Tarkista lentoni — Ilmaiseksi',
    'trust.ssl': 'SSL & GDPR Yhteensopiva', 'trust.fee': 'Ei voittoa, ei maksua — 25%',
    'trust.ai': 'Claude AI käyttöinen', 'trust.flights': 'Kaikki EU & UK lennot', 'trust.reviews': '4,8/5 · 3 841 arvostelua',
    'available_in': 'Saatavilla',
    'result.nextsteps': 'Seuraavat vaiheet:', 'result.claim_btn': 'Aloita vaatimukseni — ei ennakkomaksuja →',
    'result.estimated': 'Arvioitu:',
  },
  'el': {
    'hero.title1': 'Διεκδικήστε έως',
    'hero.title2': 'για καθυστερημένες ή ακυρωμένες πτήσεις',
    'hero.subtitle': 'Γρήγορος έλεγχος AI. Χωρίς προκαταβολή. Χρεώνουμε μόνο αν κερδίσετε.',
    'hero.cta': 'Έλεγχος πτήσης — Δωρεάν',
    'hero.how': 'Πώς λειτουργεί',
    'hero.stat.max_label': 'Μέγιστο ανά επιβάτη',
    'hero.stat.lookback_label': 'Περίοδος αναδρομής',
    'hero.stat.success_label': 'Ποσοστό επιτυχίας',
    'hero.stat.payout_label': 'Μέσος χρόνος αποζημίωσης',
    'nav.home': 'Αρχική', 'nav.about': 'Σχετικά', 'nav.how': 'Πώς λειτουργεί',
    'nav.fees': 'Αμοιβές μας', 'nav.claim': 'Νέα αξίωση', 'nav.myclaims': 'Οι αξιώσεις μου', 'nav.signin': 'Σύνδεση',
    'checker.badge': 'Δωρεάν έλεγχος AI — 60 δευτερόλεπτα',
    'checker.title': 'Ήταν επιλέξιμη η πτήση σας;',
    'checker.sub': 'Το Claude AI ελέγχει άμεσα την επιλεξιμότητα EC 261/2004.',
    'checker.from': 'Από', 'checker.to': 'Προς',
    'checker.flight': 'Αριθμός πτήσης', 'checker.date': 'Ημερομηνία πτήσης',
    'checker.airline': 'Αεροπορική', 'checker.what': 'Τι συνέβη;',
    'checker.reason': 'Αιτία αεροπορικής (προαιρετικό)',
    'checker.reason_placeholder': 'π.χ. τεχνική βλάβη, καιρός, έλλειψη πληρώματος...',
    'checker.btn': 'Έλεγχος πτήσης — Δωρεάν',
    'checker.analyzing': 'Claude AI αναλύει...',
    'checker.select': 'Επιλογή...', 'checker.select_airline': 'Επιλογή...', 'checker.select_issue': 'Επιλογή...',
    'steps.badge': 'Απλή διαδικασία', 'steps.title': '3 βήματα για την αποζημίωσή σας',
    'steps.1.title': 'Έλεγχος επιλεξιμότητας', 'steps.1.desc': 'Εισάγετε τα στοιχεία πτήσης. Το AI μας ελέγχει EC 261/2004 σε δευτερόλεπτα.',
    'steps.2.title': 'Υποβολή & υπογραφή', 'steps.2.desc': 'Ανεβάστε έγγραφα και υπογράψτε το πληρεξούσιο ψηφιακά. Κάτω από 5 λεπτά.',
    'steps.3.title': 'Λάβετε πληρωμή', 'steps.3.desc': 'Αγωνιζόμαστε με την αεροπορική. Λαμβάνετε έως €600. Παίρνουμε 25% μόνο επί επιτυχίας.',
    'faq.title': 'Συχνές ερωτήσεις', 'faq.badge': 'FAQ',
    'cta.title': 'Έτοιμοι να διεκδικήσετε ό,τι σας ανήκει;',
    'cta.sub': 'Δωρεάν έλεγχος, χωρίς δέσμευση. Χιλιάδες επιβάτες αποζημιώθηκαν.',
    'cta.btn': 'Έλεγχος πτήσης — Δωρεάν',
    'trust.ssl': 'SSL & GDPR Συμμορφούμενο', 'trust.fee': 'Χωρίς επιτυχία χωρίς χρέωση — 25%',
    'trust.ai': 'Τροφοδοτείται από Claude AI', 'trust.flights': 'Όλες οι πτήσεις ΕΕ & ΗΒ', 'trust.reviews': '4,8/5 · 3.841 κριτικές',
    'available_in': 'Διαθέσιμο σε',
    'result.nextsteps': 'Επόμενα βήματα:', 'result.claim_btn': 'Έναρξη αξίωσης — χωρίς κόστος →',
    'result.estimated': 'Εκτιμώμενο:',
  },
  'hr': {
    'hero.title1': 'Zahtijevajte do',
    'hero.title2': 'za zakašnjele ili otkazane letove',
    'hero.subtitle': 'Brza AI provjera. Bez predujma. Naplaćujemo samo pri uspjehu.',
    'hero.cta': 'Provjeri moj let — Besplatno',
    'hero.how': 'Kako funkcionira',
    'hero.stat.max_label': 'Maks. po putniku',
    'hero.stat.lookback_label': 'Retroaktivno razdoblje',
    'hero.stat.success_label': 'Stopa uspjeha',
    'hero.stat.payout_label': 'Prosječno vrijeme isplate',
    'nav.home': 'Početna', 'nav.about': 'O nama', 'nav.how': 'Kako funkcionira',
    'nav.fees': 'Naše naknade', 'nav.claim': 'Novi zahtjev', 'nav.myclaims': 'Moji zahtjevi', 'nav.signin': 'Prijavi se',
    'checker.badge': 'Besplatna AI provjera — 60 sekundi',
    'checker.title': 'Je li vaš let bio prihvatljiv?',
    'checker.sub': 'Claude AI trenutačno provjerava prihvatljivost EC 261/2004.',
    'checker.from': 'Iz', 'checker.to': 'U',
    'checker.flight': 'Broj leta', 'checker.date': 'Datum leta',
    'checker.airline': 'Zrakoplovna kompanija', 'checker.what': 'Što se dogodilo?',
    'checker.reason': 'Razlog kompanije (neobavezno)',
    'checker.reason_placeholder': 'npr. tehnički kvar, vrijeme, nedostatak posade...',
    'checker.btn': 'Provjeri moj let — Besplatno',
    'checker.analyzing': 'Claude AI analizira...',
    'checker.select': 'Odaberi...', 'checker.select_airline': 'Odaberi...', 'checker.select_issue': 'Odaberi...',
    'steps.badge': 'Jednostavan proces', 'steps.title': '3 koraka do naknade',
    'steps.1.title': 'Provjeri prihvatljivost', 'steps.1.desc': 'Unesite podatke o letu. Naš AI provjerava EC 261/2004 u sekundama.',
    'steps.2.title': 'Pošalji i potpiši', 'steps.2.desc': 'Učitajte dokumente i potpišite punomoć digitalno. Manje od 5 minuta.',
    'steps.3.title': 'Primi isplatu', 'steps.3.desc': 'Borimo se s kompanijom. Primate do €600. Uzimamo 25% samo pri uspjehu.',
    'faq.title': 'Česta pitanja', 'faq.badge': 'FAQ',
    'cta.title': 'Spremi za zahtijevanje onoga što vam pripada?',
    'cta.sub': 'Besplatna provjera, bez obveza. Tisuće putnika naplaćeno.',
    'cta.btn': 'Provjeri moj let — Besplatno',
    'trust.ssl': 'SSL & GDPR Sukladnost', 'trust.fee': 'Bez uspjeha bez naknade — 25%',
    'trust.ai': 'Pokreće Claude AI', 'trust.flights': 'Svi letovi EU & UK', 'trust.reviews': '4,8/5 · 3.841 recenzija',
    'available_in': 'Dostupno u',
    'result.nextsteps': 'Sljedeći koraci:', 'result.claim_btn': 'Pokreni zahtjev — bez troškova →',
    'result.estimated': 'Procijenjeno:',
  },
  'hu': {
    'hero.title1': 'Igényeljen akár',
    'hero.title2': 'késett vagy törölt járatok esetén',
    'hero.subtitle': 'Gyors AI-ellenőrzés. Nincs előzetes díj. Csak siker esetén számítunk fel díjat.',
    'hero.cta': 'Ellenőrizze járatom — Ingyenesen',
    'hero.how': 'Hogyan működik',
    'hero.stat.max_label': 'Max utasonként',
    'hero.stat.lookback_label': 'Visszamenőleges időszak',
    'hero.stat.success_label': 'Sikerességi arány',
    'hero.stat.payout_label': 'Átlagos kifizetési idő',
    'nav.home': 'Főoldal', 'nav.about': 'Rólunk', 'nav.how': 'Hogyan működik',
    'nav.fees': 'Díjaink', 'nav.claim': 'Új igény', 'nav.myclaims': 'Igényeim', 'nav.signin': 'Bejelentkezés',
    'checker.badge': 'Ingyenes AI-ellenőrzés — 60 másodperc',
    'checker.title': 'Jogosult volt-e a járata?',
    'checker.sub': 'A Claude AI azonnal ellenőrzi az EC 261/2004 jogosultságot.',
    'checker.from': 'Honnan', 'checker.to': 'Hova',
    'checker.flight': 'Járatszám', 'checker.date': 'Járat dátuma',
    'checker.airline': 'Légitársaság', 'checker.what': 'Mi történt?',
    'checker.reason': 'Légitársaság indoka (opcionális)',
    'checker.reason_placeholder': 'pl. műszaki hiba, időjárás, személyzethiány...',
    'checker.btn': 'Ellenőrizze járatom — Ingyenesen',
    'checker.analyzing': 'Claude AI elemez...',
    'checker.select': 'Válasszon...', 'checker.select_airline': 'Válasszon...', 'checker.select_issue': 'Válasszon...',
    'steps.badge': 'Egyszerű folyamat', 'steps.title': '3 lépés a kártérítéshez',
    'steps.1.title': 'Jogosultság ellenőrzése', 'steps.1.desc': 'Adja meg a járat adatait. AI-nk másodpercek alatt ellenőrzi az EC 261/2004-t.',
    'steps.2.title': 'Benyújtás és aláírás', 'steps.2.desc': 'Töltse fel a dokumentumokat és írja alá a meghatalmazást digitálisan. 5 percen belül.',
    'steps.3.title': 'Kifizetés fogadása', 'steps.3.desc': 'Küzdünk a légitársasággal. Akár €600-t kap. Csak siker esetén szedünk 25%-ot.',
    'faq.title': 'Gyakori kérdések', 'faq.badge': 'FAQ',
    'cta.title': 'Készen áll, hogy visszakövetelje a magáét?',
    'cta.sub': 'Ingyenes ellenőrzés, kötelezettség nélkül. Ezer utasnak fizettünk ki.',
    'cta.btn': 'Ellenőrizze járatom — Ingyenesen',
    'trust.ssl': 'SSL & GDPR Megfelelő', 'trust.fee': 'Nem siker, nem díj — 25%',
    'trust.ai': 'Claude AI alapú', 'trust.flights': 'Minden EU & UK járat', 'trust.reviews': '4,8/5 · 3 841 értékelés',
    'available_in': 'Elérhető',
    'result.nextsteps': 'Következő lépések:', 'result.claim_btn': 'Igényem indítása — előzetes költség nélkül →',
    'result.estimated': 'Becsült:',
  },
  'bg': {
    'hero.title1': 'Поискайте до',
    'hero.title2': 'за закъснели или отменени полети',
    'hero.subtitle': 'Бърза AI проверка. Без авансово плащане. Таксуваме само при успех.',
    'hero.cta': 'Провери полета ми — Безплатно',
    'hero.how': 'Как работи',
    'hero.stat.max_label': 'Макс. на пътник',
    'hero.stat.lookback_label': 'Ретроактивен период',
    'hero.stat.success_label': 'Процент на успех',
    'hero.stat.payout_label': 'Средно време за плащане',
    'nav.home': 'Начало', 'nav.about': 'За нас', 'nav.how': 'Как работи',
    'nav.fees': 'Нашите такси', 'nav.claim': 'Нова претенция', 'nav.myclaims': 'Моите претенции', 'nav.signin': 'Вход',
    'checker.badge': 'Безплатна AI проверка — 60 секунди',
    'checker.title': 'Беше ли полетът ви допустим?',
    'checker.sub': 'Claude AI незабавно проверява допустимостта по EC 261/2004.',
    'checker.from': 'От', 'checker.to': 'До',
    'checker.flight': 'Номер на полет', 'checker.date': 'Дата на полет',
    'checker.airline': 'Авиокомпания', 'checker.what': 'Какво се случи?',
    'checker.reason': 'Причина на авиокомпанията (незадължително)',
    'checker.reason_placeholder': 'напр. техническа неизправност, лошо време, липса на екипаж...',
    'checker.btn': 'Провери полета ми — Безплатно',
    'checker.analyzing': 'Claude AI анализира...',
    'checker.select': 'Изберете...', 'checker.select_airline': 'Изберете...', 'checker.select_issue': 'Изберете...',
    'steps.badge': 'Прост процес', 'steps.title': '3 стъпки до вашето обезщетение',
    'steps.1.title': 'Проверете допустимостта', 'steps.1.desc': 'Въведете данните за полета. Нашият AI проверява EC 261/2004 за секунди.',
    'steps.2.title': 'Подайте и подпишете', 'steps.2.desc': 'Качете документи и подпишете пълномощното цифрово. Под 5 минути.',
    'steps.3.title': 'Получете плащане', 'steps.3.desc': 'Борим се с авиокомпанията. Получавате до €600. Вземаме 25% само при успех.',
    'faq.title': 'Чести въпроси', 'faq.badge': 'FAQ',
    'cta.title': 'Готови да поискате своето?',
    'cta.sub': 'Безплатна проверка, без ангажимент. Хиляди пътници получиха обезщетение.',
    'cta.btn': 'Провери полета ми — Безплатно',
    'trust.ssl': 'SSL & GDPR Съответствие', 'trust.fee': 'Без успех без такса — 25%',
    'trust.ai': 'Задвижвано от Claude AI', 'trust.flights': 'Всички полети ЕС & UK', 'trust.reviews': '4,8/5 · 3 841 отзива',
    'available_in': 'Налично в',
    'result.nextsteps': 'Следващи стъпки:', 'result.claim_btn': 'Стартирай претенцията ми — без авансови разходи →',
    'result.estimated': 'Оценено:',
  },
  'sq': {
    'hero.title1': 'Kërkoni deri në',
    'hero.title2': 'për fluturime të vonuara ose të anuluara',
    'hero.subtitle': 'Kontroll i shpejtë me AI. Pa pagesë paraprake. Paguajmë vetëm nëse fitoni.',
    'hero.cta': 'Kontrolloni fluturimin tim — Falas',
    'hero.how': 'Si funksionon',
    'hero.stat.max_label': 'Maks. për pasagjer',
    'hero.stat.lookback_label': 'Periudha e kërkesës',
    'hero.stat.success_label': 'Shkalla e suksesit',
    'hero.stat.payout_label': 'Koha mesatare e pagesës',
    'nav.home': 'Kryefaqja', 'nav.about': 'Rreth nesh', 'nav.how': 'Si funksionon',
    'nav.fees': 'Tarifat tona', 'nav.claim': 'Kërkesë e re', 'nav.myclaims': 'Kërkesat e mia', 'nav.signin': 'Hyrje',
    'checker.badge': 'Kontroll falas me AI — 60 sekonda',
    'checker.title': 'A ishte fluturimi juaj i pranueshëm?',
    'checker.sub': 'Claude AI kontrollon menjëherë pranueshmërinë EC 261/2004.',
    'checker.from': 'Nga', 'checker.to': 'Në',
    'checker.flight': 'Numri i fluturimit', 'checker.date': 'Data e fluturimit',
    'checker.airline': 'Kompania ajrore', 'checker.what': 'Çfarë ndodhi?',
    'checker.reason': 'Arsyeja e kompanisë (opsionale)',
    'checker.reason_placeholder': 'p.sh. defekt teknik, mot, mungesë ekuipazhi...',
    'checker.btn': 'Kontrolloni fluturimin tim — Falas',
    'checker.analyzing': 'Claude AI po analizon...',
    'checker.select': 'Zgjidhni...', 'checker.select_airline': 'Zgjidhni...', 'checker.select_issue': 'Zgjidhni...',
    'steps.badge': 'Proces i thjeshtë', 'steps.title': '3 hapa për kompensimin tuaj',
    'steps.1.title': 'Kontrolloni pranueshmërinë', 'steps.1.desc': 'Jepni detajet e fluturimit. AI ynë kontrollon EC 261/2004 në sekonda.',
    'steps.2.title': 'Dorëzoni dhe nënshkruani', 'steps.2.desc': 'Ngarkoni dokumentet dhe nënshkruani autorizimin dixhital. Nën 5 minuta.',
    'steps.3.title': 'Merrni pagesën', 'steps.3.desc': 'Luftojmë me kompaninë ajrore. Merrni deri €600. Marrim 25% vetëm nëse fitojmë.',
    'faq.title': 'Pyetje të shpeshta', 'faq.badge': 'FAQ',
    'cta.title': 'Gati të kërkoni të drejtën tuaj?',
    'cta.sub': 'Kontroll falas, pa detyrim. Mijëra pasagjerë të paguar.',
    'cta.btn': 'Kontrolloni fluturimin tim — Falas',
    'trust.ssl': 'SSL & GDPR Konforme', 'trust.fee': 'Pa fitim pa tarifë — 25%',
    'trust.ai': 'Fuqizuar nga Claude AI', 'trust.flights': 'Të gjitha fluturimet BE & UK', 'trust.reviews': '4.8/5 · 3,841 komente',
    'available_in': 'I disponueshëm në',
    'result.nextsteps': 'Hapat e radhës:', 'result.claim_btn': 'Filloni kërkesën time — pa kosto paraprake →',
    'result.estimated': 'I vlerësuar:',
  },
  'zh': {
    'hero.title1': '索赔高达',
    'hero.title2': '针对延误或取消的航班',
    'hero.subtitle': '快速AI资格审查。无预付费用。只有胜诉才收费。',
    'hero.cta': '检查我的航班 — 免费',
    'hero.how': '如何运作',
    'hero.stat.max_label': '每位旅客最高',
    'hero.stat.lookback_label': '追溯期',
    'hero.stat.success_label': '成功率',
    'hero.stat.payout_label': '平均付款时间',
    'nav.home': '首页', 'nav.about': '关于我们', 'nav.how': '如何运作',
    'nav.fees': '我们的费用', 'nav.claim': '新索赔', 'nav.myclaims': '我的索赔', 'nav.signin': '登录',
    'checker.badge': '免费AI检查 — 60秒',
    'checker.title': '您的航班是否符合资格？',
    'checker.sub': 'Claude AI即时检查EC 261/2004资格。',
    'checker.from': '出发', 'checker.to': '到达',
    'checker.flight': '航班号', 'checker.date': '航班日期',
    'checker.airline': '航空公司', 'checker.what': '发生了什么？',
    'checker.reason': '航空公司给出的原因（可选）',
    'checker.reason_placeholder': '例如：技术故障、天气、机组人员短缺...',
    'checker.btn': '检查我的航班 — 免费',
    'checker.analyzing': 'Claude AI正在分析...',
    'checker.select': '请选择...', 'checker.select_airline': '请选择...', 'checker.select_issue': '请选择...',
    'steps.badge': '简单流程', 'steps.title': '3步获得赔偿',
    'steps.1.title': '检查资格', 'steps.1.desc': '输入航班详情。我们的AI在几秒内检查EC 261/2004。',
    'steps.2.title': '提交并签署', 'steps.2.desc': '上传文件并数字签署授权书。5分钟内完成。',
    'steps.3.title': '收取赔偿', 'steps.3.desc': '我们与航空公司交涉。您将获得高达€600。仅在胜诉时收取25%。',
    'faq.title': '常见问题', 'faq.badge': 'FAQ',
    'cta.title': '准备好索取您应得的权益了吗？',
    'cta.sub': '免费检查，无需承诺。数千名旅客已获赔偿。',
    'cta.btn': '检查我的航班 — 免费',
    'trust.ssl': 'SSL & GDPR合规', 'trust.fee': '不胜诉不收费 — 25%',
    'trust.ai': '由Claude AI驱动', 'trust.flights': '所有EU和UK航班', 'trust.reviews': '4.8/5 · 3,841条评价',
    'available_in': '可用语言',
    'result.nextsteps': '后续步骤：', 'result.claim_btn': '开始我的索赔 — 无前期费用 →',
    'result.estimated': '预计：',
  },
};

// Codes that share translations with a parent
const aliases: Record<string, string> = {
  'en-us': 'en', 'en-ca': 'en', 'en-ie': 'en', 'en-int': 'en',
  'de-at': 'de', 'de-ch': 'de',
  'fr-ca': 'fr',
  'pt-br': 'pt',
  'mo': 'ro',
};

export function getTranslations(code: string): Translations {
  const resolved = aliases[code] ?? code;
  const overrides = translations[resolved] ?? {};
  return { ...base, ...overrides };
}

// ─── Context ─────────────────────────────────────────────────────────────────

interface LangCtx {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const Ctx = createContext<LangCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('site_language');
    return LANGUAGES.find(l => l.code === saved) ?? LANGUAGES[0];
  });

  // Derive translations directly from lang — no separate state, no sync issues
  const tr = getTranslations(lang.code);

  function setLang(l: Language) {
    setLangState(l);
    localStorage.setItem('site_language', l.code);
  }

  function t(key: TranslationKey): string {
    return tr[key] ?? key;
  }

  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export function useLang() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
