ALTER TABLE claims
  ADD COLUMN IF NOT EXISTS passengers_count INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS additional_passengers TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS booking_reference TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delay_hours NUMERIC(5,1) NOT NULL DEFAULT 0;
